### ISSUE TITLE
Where to put the updates folder

### ISSUE THREAD

**Issue by cata-libuy** [keycircle/keyuxt#4]
Hi
I'm trying to create a first user for the admin, following the "Adding an update script" instructions in the [keystone getting started article](https://keystonejs.com/getting-started/setting-up/part-2).

To do that, I have turned the 'auto update' option on the init configuration to `true`, and I have tried to add an `updates` folder in the server and in the root folder with no success, I just keep receiving the error:

"KeystoneJS Update Error:

An updates folder must exist in your project root to use automatic updates.
If you want to use a custom path for your updates, set the `updates` option.
If you don't want to use updates, set the `auto update` option to `false`.
See http://keystonejs.com/docs/configuration/#updates for more information."

I think it has something to do with the build process, I appreciate any help with that.

**Comment by gngchrs** [comment]
@cata-libuy did you figure this out?

**Comment by cata-libuy** [comment]
Hi, no. I have not tried later. I was just trying this framework... I ended using express.
If I happen to continue some day and figure it out, I'll comment it here.

**Comment by itzaks** [comment]
@gangachris I put it in the `server` folder so and add then added a `updates`-field to the keystone config like this:

    import path from 'path'

    ....

    keystone.init({
      ...
      'updates': path.resolve(__dirname, './updates'),
      ...
    });

**Comment by jlopezxs** [comment]
All the project has been updated to give better support to Docker and make it easier to develop with it
